# Generated by Django 6.1.1 on 2026-09-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_post_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='picname',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='uploadername',
        ),
    ]
