# Generated by Django 6.1.1 on 2026-09-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_text_post_picname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picname',
            field=models.CharField(max_length=250),
        ),
    ]
